# Generated by Django 4.2.7 on 2023-11-04 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JacobiOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A', models.CharField(default='[]', max_length=500)),
                ('B', models.CharField(default='[]', max_length=500)),
                ('x0', models.CharField(default='[]', max_length=500)),
                ('tolerance', models.FloatField(default=1e-05)),
                ('max_iter', models.BigIntegerField(default=1)),
                ('X', models.CharField(default='[]', max_length=500, null=True)),
                ('number_iteration', models.IntegerField(default=0, null=True)),
                ('err', models.FloatField(default=0, null=True)),
                ('kind', models.CharField(default='JACOBI', max_length=200)),
                ('date_use', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
