# Generated by Django 4.2.7 on 2023-11-05 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jacobi', '0002_rename_jacobioutput_jacobi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jacobi',
            name='date_use',
        ),
    ]
