# Generated by Django 4.2.7 on 2023-11-09 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RK4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ED', models.CharField(default='t-y', max_length=500)),
                ('a', models.FloatField(default=0)),
                ('b', models.FloatField(default=1)),
                ('Z', models.FloatField(default=0)),
                ('M', models.BigIntegerField(default=10)),
                ('X', models.CharField(default='[]', max_length=1000, null=True)),
                ('kind', models.CharField(default='RK4', max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
