# Generated by Django 4.2.7 on 2023-11-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods_app', '0002_alter_numericalmethod_inputs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numericalmethod',
            name='outputs',
            field=models.JSONField(default={'test_output': 1}, null=True),
        ),
    ]
