# Generated by Django 4.2.7 on 2023-11-05 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jacobi', '0002_rename_jacobioutput_jacobi'),
        ('boolerl_app', '0003_alter_boolerloutput_aprox'),
        ('bisect_app', '0004_bisectoutput_kind'),
        ('methods_app', '0003_alter_numericalmethod_outputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='numericalmethod',
            name='bisect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bisect_app.bisectoutput'),
        ),
        migrations.AddField(
            model_name='numericalmethod',
            name='booler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boolerl_app.boolerloutput'),
        ),
        migrations.AddField(
            model_name='numericalmethod',
            name='jacobi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jacobi.jacobi'),
        ),
    ]
