# Generated by Django 4.2.7 on 2023-11-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods_app', '0004_numericalmethod_bisect_numericalmethod_booler_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numericalmethod',
            name='date_use',
            field=models.DateTimeField(null=True),
        ),
    ]
