# Generated by Django 4.2.7 on 2023-11-05 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('methods_app', '0005_alter_numericalmethod_date_use'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numericalmethod',
            old_name='booler',
            new_name='boolerl',
        ),
    ]
