# Generated by Django 4.2.6 on 2023-11-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bisect_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bisectoutput',
            name='a',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bisectoutput',
            name='b',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bisectoutput',
            name='detal',
            field=models.FloatField(default=1e-05),
        ),
        migrations.AlterField(
            model_name='bisectoutput',
            name='err',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bisectoutput',
            name='froot',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bisectoutput',
            name='root',
            field=models.FloatField(default=0, null=True),
        ),
    ]
