# Generated by Django 4.2.6 on 2023-11-02 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bisect_app', '0002_bisectoutput_a_bisectoutput_b_bisectoutput_detal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bisectoutput',
            old_name='detal',
            new_name='tolerance',
        ),
    ]
