# Generated by Django 4.2.7 on 2023-11-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bisect_app', '0003_rename_detal_bisectoutput_tolerance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bisectoutput',
            name='kind',
            field=models.CharField(default='BISECT', max_length=200),
        ),
    ]
