# Generated by Django 4.2.7 on 2023-11-05 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bisect_app', '0004_bisectoutput_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bisectoutput',
            name='date_use',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 5, 17, 55, 35, 286263)),
        ),
    ]
