# Generated by Django 4.2.7 on 2023-11-05 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bisect_app', '0005_alter_bisectoutput_date_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bisectoutput',
            name='date_use',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 5, 17, 57, 19, 563221)),
        ),
    ]
