# Generated by Django 4.2.7 on 2023-11-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bisect_app', '0006_alter_bisectoutput_date_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bisectoutput',
            name='date_use',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
