# Generated by Django 4.2.7 on 2023-11-05 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bisect_app', '0007_alter_bisectoutput_date_use'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bisectoutput',
            name='date_use',
        ),
    ]
