# Generated by Django 4.2.7 on 2023-11-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bisect_app', '0008_remove_bisectoutput_date_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bisectoutput',
            name='a',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bisectoutput',
            name='b',
            field=models.FloatField(default=1),
        ),
    ]
