# Generated by Django 4.2.7 on 2023-11-04 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoolerlOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_s', models.CharField(max_length=200)),
                ('a', models.IntegerField(default=0)),
                ('b', models.IntegerField(default=1)),
                ('M', models.BigIntegerField(default=4)),
                ('aprox', models.FloatField(default=0)),
                ('kind', models.CharField(default='BOOLERL', max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
