# Generated by Django 4.2.7 on 2023-11-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boolerl_app', '0002_alter_boolerloutput_a_alter_boolerloutput_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boolerloutput',
            name='aprox',
            field=models.FloatField(default=0, null=True),
        ),
    ]
